### PR TITLE
feat: allow setting main-branch-name via environment variable

### PR DESCRIPTION
**Pull request by mattlewis92**
For our CI system we have the concept of multiple main branches. We enabled the "Only build pull requests" option in circleci so that we could reliably determine the base branch based on the PR. However due to a limitation in circle we aren't able to dynamically pass the main branch name after we've computed it from the pull request. As a workaround it would be great if there was a simple environment variable that we could set instead of relying on the circleci parameter to set the main branch name. I'm opening this PR for further discussion.

### CODE REVIEW

**Comment by meeroslav** [comment]
NX_... environment variables are defined within the Nx codebase and are used by the core functionality. This one only refers to your current run and is passed to CircleCI API, so it shouldn't have `NX_` prefix.

But generally, I'm not sure how setting the environment variable is better than passing a parameter to `nx-set-shas` like seen here: https://github.com/nrwl/nx-orb/blob/main/src/examples/custom.yml#L20

Can you elaborate on why the above parameter doesn't work? Perhaps you can paste a snippet of your CI yaml config.

**Comment by mattlewis92** [comment]
> NX_... environment variables are defined within the Nx codebase and are used by the core functionality. This one only refers to your current run and is passed to CircleCI API, so it shouldn't have NX_ prefix.

That makes sense, can you suggest a better name for it?

> Can you elaborate on why the above parameter doesn't work? Perhaps you can paste a snippet of your CI yaml config.

Sure thing, we're trying to dynamically set the main branch name from an environment variable like this:


```
      - nx/set-shas:
          main-branch-name: $NX_MAIN_BRANCH
```

Before this we have a step which dynamically determines the main branch to use based on if it's a pull request or not like this:

```
if [[ $CIRCLE_PULL_REQUEST == '' ]]; then
	  # If not building a PR then it means we're building a main branch
	  # so we look for the last successful commit on the current branch
	  echo "NX_MAIN_BRANCH: $CIRCLE_BRANCH"
	  echo "export NX_MAIN_BRANCH='$CIRCLE_BRANCH'" >>$BASH_ENV
else 
      # It's a pull request, use the base branch from the PR
	  PR_NUMBER=$(echo "$CIRCLE_PULL_REQUEST" | sed "s/.*\/pull\///")
	  echo "PR_NUMBER: $PR_NUMBER"
	  echo "export GITHUB_PR_NUMBER=$PR_NUMBER" >>$BASH_ENV
	  
	  API_GITHUB="https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME"
	  PR_REQUEST_URL="$API_GITHUB/pulls/$PR_NUMBER"
	  PR_RESPONSE=$(curl -H "Authorization: token $github_access_token" "$PR_REQUEST_URL")
	  
	  PR_BASE_BRANCH=$(echo $PR_RESPONSE | jq -e '.base.ref' | tr -d '"')
	  echo "NX_MAIN_BRANCH: $PR_BASE_BRANCH"
	  echo "export NX_MAIN_BRANCH='$PR_BASE_BRANCH'" >>$BASH_ENV
fi
```

According to circleci's support there is no way to dynamically pass the parameter like this so they suggested making a PR here to add the functionality:
CleanShot 2022-03-22 at 10 24 48@2x

**Comment by meeroslav** [comment]
> That makes sense, can you suggest a better name for it?

Just name it `MAIN_BRANCH_NAME`, the same as the param.

**Comment by mattlewis92** [comment]
> > That makes sense, can you suggest a better name for it?
> 
> Just name it `MAIN_BRANCH_NAME`, the same as the param.

Done!

**Comment by meeroslav** [comment]
Thank you!

**Comment by mattlewis92** [comment]
@meeroslav it looks like the build [did not publish](https://app.circleci.com/pipelines/github/nrwl/nx-orb/123/workflows/17608cef-c0a9-42be-9a5d-0cd47391527d/jobs/300) as the commit message was wrong, could you take a look please? 😄

**Comment by meeroslav** [comment]
Yes, @mattlewis92, I will publish it today.

**Comment by mattlewis92** [comment]
Awesome, thank you so much! 🙌

**Pull request merged**
